### ISSUE TITLE
Any chance for Overseer DVD compatibility?

### ISSUE THREAD

**Issue by supercom32** [ElakaSnarne/WinTex#16]
Hi there,

This is a long shot, but does this project have any plans to add compatibility for Overseer (DVD)? The reason I ask is because it's clearly the game which needs this kind of treatment the most, since it doesn't actually run on modern windows systems without significant modifications.

**Comment by ElakaSnarne** [comment]
At the moment WinTex only supports Under a Killing Moon, with work being done for Pandora Directive. These 2 games share file formats (main difference is in media and scripting engine). Overseer would be a completely different monster, so it would likely have to be a separate project.
